name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.14.0'
      - name: Install modules
        run: yarn install
      - name: Check linting
        run: yarn lint:check
      - name: Build
        run: yarn build
      - name: Test
        run: yarn test
